# Generated by Django 4.1.1 on 2022-09-25 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_education_candidate_alter_experience_candidate_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Links',
            new_name='Link',
        ),
    ]
